export interface IContract {
  id: string,
  client: string,
  clientId: string,
  numero: string,
  suplemento: string,
  numeroSuplement: number,
  fechaEntrega: Date,
  fechaFirma: Date,
  fechaRecibido: Date,
  instalador: string,
  idInstalador: string,
  ubicacion: string,
  objeto: string,
  importeLicenciasCUC: number,
  importeLicenciasMN: number,
  importePostVentaCUC: number,
  importePostVentaMN: number,
  mesInicioPostVenta: number,
  mesFinalPostVenta: number,
  anoFinalPostVenta: number,
  master: string,
  discontinued: boolean
}
